### ISSUE TITLE
put in requirements in the readme

### ISSUE THREAD

**Issue by siddharth-joshi** [Intelligent-Microsystems-Lab/SNNQuantPrune#1]
Could you also include what package/requirements you have in the readme? E.g., do you need JAX? FLAX? Tensorflow?

**Comment by clee1994** [comment]
Added in last commit :)

**Comment by siddharth-joshi** [comment]
> Added in last commit :)

oops my bad! Should have checked the branches too! Thanks! Could you add TCAS and link to the ARXIV :)
